### ISSUE TITLE
sbt 1.4

### ISSUE THREAD

**Issue by ennru** [lightbend/sbt-paradox-dependencies#24]
As sbt now contains the dependency tree functionality, this plugin needs to drop its dependency on sbt-dependency-graph.

**Comment by raboof** [comment]
hmm, does this mean we cannot publish a version of sbt-paradox-dependencies that works both with sbt 1.4.x and with 1.3.x? I guess that's probably fine in our case.

**Comment by ennru** [comment]
That's my understanding, the same tasks use different classes now.
It will require picking an sbt-paradox-dependencies version that aligns with the sbt minor version.

**Comment by raboof** [comment]
Added https://github.com/sbt/sbt/issues/5894

**Comment by ennru** [comment]
Expected to be fixed with https://github.com/sbt/sbt/pull/5914
